import { env, introspectWorkflow } from "cloudflare:test";
import { beforeEach, describe, expect, test } from "vitest";
import worker, { __setAppBotLoginForTests } from "../main";
import issuesAssigned from "./fixtures/issues-assigned.json";
import issuesClosed from "./fixtures/issues-closed.json";
import pushDefaultBranch from "./fixtures/push-default-branch.json";
import { buildSignedWebhookRequest } from "./workflow-test-helpers";

// Pre-seed the bot-login cache so the handler doesn't call `GET /app`.
beforeEach(() => {
	__setAppBotLoginForTests("xmtp-coder-tasks[bot]");
});

// `env` from `cloudflare:test` is typed as the `Cloudflare.Env` generated by
// `wrangler types`, which includes only `[vars]` entries — not the secrets we
// inject via `miniflare.bindings` in `vitest.config.ts`. Cast at the single
// entrypoint so the test body stays readable.
type TestEnv = typeof env & {
	APP_ID: string;
	PRIVATE_KEY: string;
	WEBHOOK_SECRET: string;
	CODER_TOKEN: string;
};
const testEnv = env as TestEnv;
type WorkerEnv = Parameters<typeof worker.fetch>[1];

/**
 * End-to-end signed-webhook → worker fetch handler → real env.TASK_RUNNER_WORKFLOW
 * → introspected workflow completion. Only test in the suite exercising the
 * full pipeline including:
 *
 *   • HMAC signature verification
 *   • WebhookRouter classification
 *   • `env.TASK_RUNNER_WORKFLOW.create({ id, params })` on the real binding
 *   • Workflow `run()` dispatch to the correct step factory
 *   • Introspection-driven step-result mocks
 *   • `waitForStatus("complete")` confirming the instance ran to completion
 *
 * Verifies: valid signature → 202 in <1s, and end-to-end dispatch through an
 * introspected workflow instance with `await using` disposal (no live
 * GitHub/Coder fetches). See src/testing/AGENTS.md for the pattern.
 */
describe("e2e: signed webhook → worker → workflow completion", () => {
	test("task_requested webhook runs the full pipeline to instance completion", async () => {
		await using introspector = await introspectWorkflow(
			testEnv.TASK_RUNNER_WORKFLOW,
		);
		await introspector.modifyAll(async (m) => {
			await m.disableSleeps();
			await m.mockStepResult({ name: "lookup-coder-user" }, "coder-user");
			await m.mockStepResult({ name: "check-github-permission" }, true);
			await m.mockStepResult(
				{ name: "create-coder-task" },
				{
					taskName: "gh-coder-action-65",
					owner: "coder-user",
					taskId: "11111111-1111-4111-8111-111111111111",
					url: "https://coder.example.com/tasks/coder-user/abc",
					status: "ready",
				},
			);
			await m.mockStepResult({ name: "comment-on-issue" }, {});
			// waitForTaskActive pre-poll fast-path.
			await m.mockStepResult(
				{ name: "wait-lookup-task" },
				{ status: "active" },
			);
			await m.mockStepResult({ name: "update-status-comment" }, {});
		});

		const req = await buildSignedWebhookRequest({
			secret: testEnv.WEBHOOK_SECRET,
			body: JSON.stringify(issuesAssigned),
			eventName: "issues",
			deliveryId: "e2e-delivery-1",
		});
		const started = Date.now();
		const res = await worker.fetch(
			req,
			testEnv as WorkerEnv,
			{} as ExecutionContext,
		);
		const elapsed = Date.now() - started;

		expect(res.status).toBe(202);
		expect(elapsed).toBeLessThan(1000); // 202 within 1 second

		const instances = introspector.get();
		expect(instances.length).toBeGreaterThanOrEqual(1);
		for (const inst of instances) {
			await expect(inst.waitForStatus("complete")).resolves.not.toThrow();
		}
	});

	test("task_closed webhook runs delete → comment to completion", async () => {
		await using introspector = await introspectWorkflow(
			testEnv.TASK_RUNNER_WORKFLOW,
		);
		await introspector.modifyAll(async (m) => {
			await m.disableSleeps();
			await m.mockStepResult({ name: "delete-coder-task" }, { deleted: true });
			await m.mockStepResult({ name: "comment-on-issue" }, {});
		});

		const req = await buildSignedWebhookRequest({
			secret: testEnv.WEBHOOK_SECRET,
			body: JSON.stringify(issuesClosed),
			eventName: "issues",
			deliveryId: "e2e-delivery-close-1",
		});
		const res = await worker.fetch(
			req,
			testEnv as WorkerEnv,
			{} as ExecutionContext,
		);
		expect(res.status).toBe(202);

		const instances = introspector.get();
		expect(instances.length).toBeGreaterThanOrEqual(1);
		for (const inst of instances) {
			await expect(inst.waitForStatus("complete")).resolves.not.toThrow();
		}
	});

	test("push to default branch runs RepoConfigWorkflow to completion", async () => {
		await using introspector = await introspectWorkflow(
			testEnv.REPO_CONFIG_WORKFLOW,
		);
		await introspector.modifyAll(async (m) => {
			await m.disableSleeps();
			await m.mockStepResult(
				{ name: "fetch-config-file" },
				{ present: true, contentBase64: "" },
			);
			await m.mockStepResult({ name: "parse-and-validate" }, { settings: {} });
			await m.mockStepResult({ name: "store-repo-config" }, { ok: true });
		});

		const req = await buildSignedWebhookRequest({
			secret: testEnv.WEBHOOK_SECRET,
			body: JSON.stringify(pushDefaultBranch),
			eventName: "push",
			deliveryId: "e2e-push-default-1",
		});
		const res = await worker.fetch(
			req,
			testEnv as WorkerEnv,
			{} as ExecutionContext,
		);
		expect(res.status).toBe(202);

		const instances = introspector.get();
		expect(instances.length).toBeGreaterThanOrEqual(1);
		for (const inst of instances) {
			await expect(inst.waitForStatus("complete")).resolves.not.toThrow();
		}
	});

	test("push to non-default branch is skipped (no workflow instance)", async () => {
		await using repoCfgIntrospector = await introspectWorkflow(
			testEnv.REPO_CONFIG_WORKFLOW,
		);
		await using taskIntrospector = await introspectWorkflow(
			testEnv.TASK_RUNNER_WORKFLOW,
		);

		const nonDefaultPush = {
			...pushDefaultBranch,
			ref: "refs/heads/feature",
		};
		const req = await buildSignedWebhookRequest({
			secret: testEnv.WEBHOOK_SECRET,
			body: JSON.stringify(nonDefaultPush),
			eventName: "push",
			deliveryId: "e2e-push-feature-1",
		});
		const res = await worker.fetch(
			req,
			testEnv as WorkerEnv,
			{} as ExecutionContext,
		);
		expect(res.status).toBe(200);
		expect(repoCfgIntrospector.get()).toHaveLength(0);
		expect(taskIntrospector.get()).toHaveLength(0);
	});
});
