name: Coder Failed Check Forwarding

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]

permissions:
  actions: read
  issues: write
  pull-requests: read
  contents: read

jobs:
  failed-check:
    runs-on: ubuntu-latest
    if: >-
      github.event.workflow_run.conclusion == 'failure'
    steps:
      - name: Forward Failed Check to Coder Task
        uses: xmtplabs/coder-action@main
        with:
          action: failed_check
          coder-url: ${{ secrets.CODER_URL }}
          coder-token: ${{ secrets.CODER_TOKEN }}
          coder-username: ${{ secrets.CODER_USERNAME }}
          github-token: ${{ secrets.CODER_GH_PAT }}
