name: Terraform Lint

on:
  pull_request:
    paths:
      - "terraform/**"
      - ".github/workflows/terraform-lint.yaml"

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.8"
          terraform_wrapper: false

      - name: terraform fmt
        run: terraform fmt -check -recursive -diff

      - uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: v0.53.0

      - name: tflint --init
        run: tflint --init
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: tflint
        run: tflint --recursive --format compact
